services:
    kernel.listener.locale_detector_listener:
        class: Lunetics\LocaleBundle\EventListener\LocaleDetectorListener
        arguments:
            - %locale%
            - %lunetics_locale.allowed_languages%
            - @logger
        calls:
            - [ setEventDispatcher, [@event_dispatcher] ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onRequest }