language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  - SYMFONY_VERSION='3.3.*'

matrix:
  include:
    - php: 5.5
      env:
        - COMPOSER_FLAGS="--prefer-lowest"
        - SYMFONY_VERSION='2.8.*'
    - php: 7.1
      env:
      env:
        - SYMFONY_VERSION='2.8.*'
    - php: 7.1
      env:
        - SYMFONY_VERSION='3.1.*'
    - php: 7.1
      env:
        - SYMFONY_VERSION='3.2.*'
    - php: hhvm
      dist: trusty

before_install:
  - phpenv config-rm xdebug.ini || true
  - php -i | grep "ICU version"
  - composer self-update
  - composer require symfony/symfony:${SYMFONY_VERSION} --no-update

install: composer update --prefer-dist

script: phpunit

notifications:
  email:
    - willemsen.christophe@gmail.com
    - mb@lunetics.com
