language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  - SYMFONY_VERSION=2.2.11
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.4.*
  - SYMFONY_VERSION=2.5.*
  - SYMFONY_VERSION=2.6.*

before_script:
  - php -i | grep "ICU version"
  - composer self-update
  - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
  - composer install --dev --prefer-source

script: phpunit --coverage-text

matrix:
  allow_failures:
    - env: SYMFONY_VERSION=2.4.*

notifications:
  email:
    - willemsen.christophe@gmail.com
    - mb@lunetics.com
